---

- name: wat
  debug:
    var: audio_client

- name: client config
  include_tasks:
    file: client.yml
  when: audio_client
      
- name: server config
  include_tasks:
    file: server.yml
  when: audio_server
