- name: restart avahi-daemon
  become: yes
  systemd:
    name=avahi-daemon
    state=restarted
- name: "reload udev rules"
  become: yes
  command: udevadm control --reload-rules
  listen: "reload udev rules"
- name: "udev trigger"
  become: yes
  command: udevadm trigger
  listen: "reload udev rules"
- name: "stop shairport"
  become: yes
  systemd:
    name: "shairport-sync.target"
    state: stopped
  ignore_errors: true
  listen: "reload systemd"
- name: "restart bluetooth"
  become: yes
  systemd:
    name: "bluetooth.service"
    state: restarted
  listen: "restart bluetooth"
- name: "reload systemd"
  become: yes
  systemd:
    daemon_reload: yes
  listen: "reload systemd"
- name: "reload systemd"
  become: yes
  systemd:
    daemon_reload: yes
  listen: "load systemd"
- name: check if pulseaudio running
  command: "pulseaudio --check"
  register: pa_running
  ignore_errors: yes
  listen:
    - "stop pulseaudio"
    - "restart pulseaudio"
    - "reload alsa"
    - "reload systemd"
- name: "kill pulseaudio"
  command: pulseaudio -k
  when: pa_running is succeeded
  listen:
    - "stop pulseaudio"
    - "restart pulseaudio"
    - "reload systemd"
- name: "restart pulseaudio client"
  systemd:
    name: pulseaudio
    enabled: yes
    state: restarted
    # might only work when logged in, see note in ansible systemd manpage
    scope: user
  listen: "restart pulseaudio client"
- name: "restart pulseaudio daemon"
  become: true
  systemd:
    name: "pulseaudio.service"
    enabled: yes
    state: restarted
  listen:
    - "restart pulseaudio"
    - "reload systemd"
- name: "start shairport"
  become: yes
  systemd:
    name: "shairport-sync.target"
    state: restarted
  listen:
    - "restart shairport"
    - "restart pulseaudio"
    - "reload systemd"
    - "reload alsa"
- name: "restart gmrender"
  become: yes
  systemd:
    name: "gmrender-resurrect.target"
    state: restarted
  listen:
    - "restart gmrender"
    - "restart shairport"
    - "restart pulseaudio"
    - "reload systemd"
    - "reload alsa"
